apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-auth-graph-deployment
  namespace: microservices
  labels:
    app: microservice-auth-graph-deployment
    moduleid: microservice-auth-graph-service
    version: 1.0.0-master
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservice-auth-graph-deployment
  template:
    metadata:
      labels:
        app: microservice-auth-graph-deployment
    spec:
      containers:
        -
          name: microservice-auth-graph-container
          image: '919446158824.dkr.ecr.us-east-1.amazonaws.com/microservice-auth-graph-container'
          env:
            -
              name: SERVICE_PORT
              value: '${SERVICE_PORT@microservice-auth-graph-config}'
          ports:
            -
              containerPort: '${SERVICE_PORT@microservice-auth-graph-config}'
