apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-auth-graph-deployment
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    app: microservice-auth-graph-deployment
    moduleid: microservice-auth-graph-service
    version: 1.70.1-master
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-auth-graph-deployment
  template:
    metadata:
      labels:
        app: microservice-auth-graph-deployment
    spec:
      containers:
        -
          name: app
          image: 'repoflow/microservice-auth-graph-container:1.70.1-master'
          env:
            -
              name: PATH_URL_GRAPH
              value: '${PATH_URL_GRAPH@microservice-auth-config}'
            -
              name: PATH_URL_EVENTS
              value: '${PATH_URL_EVENTS@microservice-auth-config}'
            -
              name: PORT
              value: '${PORT_GRAPH@microservice-auth-config}'
            -
              name: URL_DATA
              value: 'microservice-auth-data.${NAMESPACE@microservice-config}'
            -
              name: PORT_DATA
              value: '27017'
          ports:
            -
              containerPort: ${PORT_GRAPH@microservice-auth-config}
