apiVersion: apps/v1
kind: Deployment
metadata:
  name: '${DEPLOYMENT_GRAPH@microservice-auth-config}'
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    app: '${DEPLOYMENT_GRAPH@microservice-auth-config}'
    moduleid: microservice-auth-graph-service
    version: 1.70.2-master
spec:
  replicas: 2
  selector:
    matchLabels:
      app: '${DEPLOYMENT_GRAPH@microservice-auth-config}'
  template:
    metadata:
      labels:
        app: '${DEPLOYMENT_GRAPH@microservice-auth-config}'
    spec:
      containers:
        -
          name: app
          image: 'repoflow/microservice-auth-graph-container:1.70.2-master'
          env:
            -
              name: ROUTE_GRAPH
              value: '${ROUTE_GRAPH@microservice-auth-config}'
            -
              name: ROUTE_EVENTS
              value: '${ROUTE_EVENTS@microservice-auth-config}'
            -
              name: INTERNAL_PORT_GRAPH
              value: '${INTERNAL_PORT_GRAPH@microservice-auth-config}'
            -
              name: INTERNAL_URL_DATA
              value: '${INTERNAL_URL_DATA@microservice-auth-config}'
            -
              name: INTERNAL_HOST_CACHE
              value: '${INTERNAL_HOST_CACHE@microservice-auth-config}'
            -
              name: INTERNAL_PORT_CACHE
              value: '${INTERNAL_PORT_CACHE@microservice-auth-config}'
            -
              name: SECRET_PASSWORD_CACHE
              value: SECRET_PASSWORD_CACHE
          ports:
            -
              containerPort: '${INTERNAL_PORT_GRAPH@microservice-auth-config}'
