apiVersion: v1
kind: Service
metadata:
  name: auth-graph-service
  namespace: microservices
  labels:
    moduleid: microservice-auth-graph-service
    version: 1.0.0-master
spec:
  type: NodePort
  selector:
    app: auth-graph-deployment
  ports:
    -
      name: auth-graph-port
      port: '${SERVICE_PORT}'
