apiVersion: v1
kind: Service
metadata:
  name: microservice-auth-graph-service
  namespace: ${NAMESPACE@microservice-config}
  labels:
    moduleid: microservice-auth-graph-service
    version: 1.0.0-master
spec:
  type: NodePort
  selector:
    app: microservice-auth-graph-deployment
  ports:
    -
      name: microservice-auth-graph-port
      port: ${SERVICE_PORT@microservice-auth-graph-config}
