apiVersion: v1
kind: Service
metadata:
  name: '${SERVICE_GRAPH@microservice-auth-config}'
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    moduleid: microservice-auth-graph-service
    version: 1.70.2-master
spec:
  type: NodePort
  selector:
    app: '${DEPLOYMENT_GRAPH@microservice-auth-config}'
  ports:
    -
      name: microservice-auth-graph-port
      port: '${INTERNAL_PORT_GRAPH@microservice-auth-config}'
